# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"read_datasets": "10_Exploring-the-Crono-MA-XRF-HDF5-file-format.ipynb",
         "report": "10_Exploring-the-Crono-MA-XRF-HDF5-file-format.ipynb",
         "peek_inside": "10_Exploring-the-Crono-MA-XRF-HDF5-file-format.ipynb",
         "download": "15_Download-demo-data.ipynb"}

modules = ["crono.py",
           "data.py"]

doc_url = "https://fligt.github.io/"

git_url = "https://github.com/fligt/cronomaxrf/tree/main/"

def custom_doc_links(name): return None
