# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"report": "10_Exploring-the-Crono-MA-XRF-HDF5-file-format.ipynb"}

modules = ["crono.py"]

doc_url = "https://fligt.github.io/cronomaxrf/"

git_url = "https://github.com/fligt/cronomaxrf/tree/main/"

def custom_doc_links(name): return None
