# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://fligt.github.io/crono-maxrf/"

git_url = "https://github.com/fligt/crono-maxrf/tree/main/"

def custom_doc_links(name): return None
